#!/bin/bash  
#Purpose: Draw scatters from Height and phases value
#Written by Zhongbo Hu @UPC 
#Email:huzhongbocumt@gmail.com
#v1.0 28/04/2016

#############################################################
################ Please Read it before using ################
#############################################################
#1.Files used for drawing is Binary format data. In the case these files generated by IDL
#  These data have n lines and 2 columns
#2.The parameters ps,J,R,Bx,By would be different in another case. Change it according to specific needs
#3.Specific "work_dir" firstly, in which there is data file.
#4.The script will draw all the data in the working directories, with the same name of input files
#5.In the same folder with the data, the temporal and spatial baseline file should be included.

#Draw Scatters image from Binary data(Canillo for example)

#============parameters need to know before processing =========== 
work_dir="/home/user/InSAR_Results/12Canillo_SPOT/one/"
J=X18c/13c
#Bx=xa25f5  
#By=ya25f5 
R=1200/2200/-3.2/3.2
Bx=xafg  
By=ya1fg


#============Start processing =========== 
cd $work_dir

Tbaseline=($(awk '{printf("%.0f\n"), $1}' *.txt))
Sbaseline=($(awk '{printf("%.1f\n"), $2}' *.txt))

for file_name in $work_dir/*.dat; do

	temp_file=`basename $file_name`
	file_name_short=${temp_file%.*}    #Get the file name without the suffix
	ps=${file_name_short}.ps

	#To avoid the problem of -K -O
	gmt psxy -J$J -R$R -T -K > $ps 

	gmt psbasemap -R$R -J$J -B$Bx -B$By -Xc -Yc \
	-Bx+l"Height" -By+l"Phase_Value"\
    -BnWSe+t"${file_name_short}/B=${Sbaseline[$index]}/T=${Tbaseline[$index]}" -K -O >> $ps
     ((index+=1))

	#Plot the symbol of  the point with specific color
	gmt psxy ${file_name_short}.dat -bi2f -R$R -J$J -Sc0.05c -Gblack -K -O >> $ps

	#To avoid the problem of -K -O
	gmt psxy -J$J -R$R -T -O >> $ps  

    rm -f gmt.*

done
