#!/bin/bash  
#Purpose: plot line or lines with different symbols and colors
#Written by Zhongbo Hu @UPC 
#Email:huzhongbocumt@gmail.com
#v1.0 17/02/2016

#############################################################
################ Please Read it before using ################
#############################################################
#1.Data file should have the specific format(i*.dat). e.g:1coeff_d.dat
#2.Files used for plotting is Binary format data. In the case these files generated by IDL
#  These data have n lines and 2 columns
#3.In this case, four lines with different colors and symbols are drown. If the number of line is different, 
#  it is nessary to change the "array_color" and "array_symbol" parameters.
#4.The parameters ps,J,R,Bx,By would be different in another case. Change it according to specific needs
#5.Specific "work_dir" firstly, in which there are data files.

#============parameters need to know before processing =========== 
work_dir="/home/SOFTWARES/GMT/t6_draw_legend"
ps=line_legend.ps
J=X20c/14c
R=0/136/-0.012/0.01
R1=0/20/0/14  #To display pscontext
Bx=xa20f5  #Bx=afg  #automatically devide and lable the x axis
By=ya0.005f0.0025  #By=afg  #automatically devide and lable the y axis

#============Start processing =========== 
cd $work_dir

#To avoid the problem of -K -O
gmt psxy -J$J -R$R -T -K > $ps   

#Generate the basemap
gmt psbasemap -R$R -J$J -B$Bx -B$By -Xc -Yc \
         -Bx+l"Index of Interferograms" -By+l"Values"\
         -BnWSe+t"Comparison between estimate and real values" -K > $ps

#Plot the line and symbol of first data (one specific example of the loop processing)
gmt psxy 1coeff_d.dat -bi2f -R$R -J$J -W0.6p,green,solid -K -O >> $ps
gmt psxy 1coeff_d.dat -bi2f -R$R -J$J -Sc0.1c -K -O >> $ps

gmt psxy 4est_coeff_d.dat -bi2f -R$R -J$J -W0.6p,red,solid -K -O >> $ps
gmt psxy 4est_coeff_d.dat -bi2f -R$R -J$J -Sc0.1c -K -O >> $ps

gmt pslegend -J$J -R$R -D

#To avoid the problem of -K -O
gmt psxy -J$J -R$R -T -O >> $ps  

