#!/bin/bash  
#Purpose: Draw scatters images
#Written by Zhongbo Hu @UPC 
#Email:huzhongbocumt@gmail.com
#v1.0 22/02/2016

#############################################################
################ Please Read it before using ################
#############################################################
#1.Files used for drawing is Binary format data. In the case these files generated by IDL
#  These data have n lines and 3 columns
#2.The parameters ps,J,R,Bx,By would be different in another case. Change it according to specific needs
#3.Specific "work_dir" firstly, in which there is data file.
#4.The script will draw all the data in the working directories, with the same name of input files

#Draw Scatters image from Binary data(Canillo for example)
if [ 1 -eq 1 ]
   then 
#============parameters need to know before processing =========== 
work_dir="/home/InSAR_Results/10Linear_DEM_Top_Turb_small/est_TopAPS_phase/"
J=X18c/18c
#R=-2/257/-2/257
#Bx=xa25f5  
#By=ya25f5 
R=-2/257/-2/257
Bx=xafg  
By=yafg 


#============Start processing =========== 
cd $work_dir

for file_name in $work_dir/*.dat; do

	temp_file=`basename $file_name`
	file_name_short=${temp_file%.*}    #Get the file name without the suffix
	ps=${file_name_short}.ps
	Figure_name=${file_name_short#1??}

	#To avoid the problem of -K -O
	gmt psxy -J$J -R$R -T -K > $ps 

	gmt psbasemap -R$R -J$J -B$Bx -B$By -Xc -Yc \
	-Bx+l"Samples" -By+l"Lines"\
	-BnWSe+t"${Figure_name}" -K -O >> $ps

	#Generate .cpt file
	gmt makecpt -T-3.14159/3.14159/0.2 -Z > new.cpt

	#Plot the symbol of  the point with different colors 
	gmt psxy ${file_name_short}.dat -bi3f -R$R -J$J -Sc0.2c -Cnew.cpt -K -O >> $ps

	#Imaging color scale
#	gmt psscale -D18.5c/6.5c/12c/0.8c -Cnew.cpt -E -B0.5 -P -K -O >> $ps
	gmt psscale -Dx18.5c/0.5c+e+w12c/0.8c -Cnew.cpt -B0.5 -P -K -O >> $ps

	#To avoid the problem of -K -O
	gmt psxy -J$J -R$R -T -O >> $ps  

    rm -f gmt.* new.cpt

done

fi





#Draw_scatters from ASCII data(CangZhou deformation data for example)

if [ 1 -eq 2 ]
   then 
#============parameters need to know before processing =========== 
work_dir="/home/SOFTWARES/GMT/t6_draw_scatters_Binary_ASCII/ASCII_DATA_CANGZHOU"
J=M16c
R=116.4/117.3/38/38.63
Bx=xa0.25f0.125g0.25
By=ya0.25f0.125g0.25
ps=CangZhou.ps

#============Start processing =========== 
cd $work_dir

#To avoid the problem of -K -O
	gmt psxy -J$J -R$R -T -K -V > $ps 

gmt psbasemap -R$R -J$J -B$Bx -B$By -Xc -Yc \
	-BnWSe+t"Deformation of CangZhou" -K -O >> $ps

#Generate .cpt file
     gmt makecpt -Cseis.cpt -T-33.35/23/0.005 -Z > new.cpt

#Plot the symbol of  the point with different colors 
     gmt psxy CangZhou.txt -R$R -J$J -Sc0.05c -Cnew.cpt -K -O >> $ps

#Imaging color scale
	gmt psscale -D17c/6.5c/12c/0.8c -Cnew.cpt -E -B5 -P -K -O >> $ps

#To avoid the problem of -K -O
	gmt psxy -J$J -R$R -T -O >> $ps  

rm -f gmt.* new.cpt

fi
